ovirt-prometheus-bridge:
  image: rmohr/ovirt-prometheus-bridge
  volumes:
    - /targets
  command: ["-no-verify", "-engine-url=https://${HOSTIP}:8443", "-output=/targets/hosts.json"]
  environment:
    - ENGINE_PASSWORD
prometheus:
  image: prom/prometheus
  volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
    - /prometheus
  ports:
    - "9090:9090"
  volumes_from:
    - ovirt-prometheus-bridge
grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  volumes:
    - /var/lib/grafana
  links:
    - prometheus
